# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFO1_rmMl3NO4O2MTySP8CDkac3vt0yv
"""

from IPython.display import display, HTML

file_path = 'scattertext_visualization.html'

with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

display(HTML(html_content))